import { useState, useCallback } from 'react';

/**
 * Hook to interact with a local Ollama endpoint.
 * NOTE: In a real environment, the API route '/api/ollama/generate' must be exposed 
 * by your backend server (e.g., Node.js/Express or Next.js API route) to handle the 'ollama' request.
 */
export const useOllamaApi = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    /**
     * Sends a prompt to the local Ollama model and returns the generated text.
     * @param prompt The prompt text to send to the model.
     * @returns A promise that resolves with the model's response.
     */
    const generateContent = useCallback(async (prompt: string): Promise<string> => {
        if (!prompt.trim()) {
            throw new Error("Prompt cannot be empty.");
        }
        
        setIsLoading(true);
        setError(null);

        // --- SIMULATION START ---
        // Because we don't have a live backend, we simulate the network latency and a successful response.
        // In a live environment, this fetch call would go to: 
        // const response = await fetch('/api/ollama/generate', { method: 'POST', body: JSON.stringify({ prompt }) });
        // const data = await response.json();
        // return data.response;
        
        try {
            // Simulate network latency
            await new Promise(resolve => setTimeout(resolve, 1500));

            // Check for specific keywords to provide a tailored simulation response
            if (prompt.toLowerCase().includes("policy")) {
                return "Based on your request, a draft policy on remote work should include three key pillars: mandatory core hours (10 AM - 3 PM), a minimum of 3 in-office days per month, and mandatory two-week equipment check-in.";
            } else if (prompt.toLowerCase().includes("users")) {
                return "The user directory indicates the following: There are 4 active users, 2 in Marketing, and the system needs a policy update to handle Department separation.";
            } else {
                return `✨ AI Assistant Output: I processed your request: "${prompt}". This is a simulated response generated by your local Ollama model. The tone is informative, and the content is ready for review!`;
            }
        } catch (err) {
            console.error("Ollama API Error Simulation:", err);
            throw new Error("Failed to connect to the local LLM service. Ensure Ollama is running and the API route is active.");
        } finally {
            setIsLoading(false);
        }
        // --- SIMULATION END ---
    }, []);

    return { generateContent, isLoading, error };
};